### ISSUE TITLE
GSoC24 - Refactoring the `src/index.js` file

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs-community/node-neutralino#13]
Currently, the entire package core resides inside this file and it looks complex for contributors, so we need to decompose it into several classes via composition. 

Idea:

- `NeutralinoApp`: The main app creation class
- `WebSocketIPC`: Websocket connection code (bind with composition) (This also hosts `OfflineMessageQueue`)
- `NeutralinoProcess`: Spawning the framework child process
- `os`, `app`, `clipboard`, classes for holding native methods

Please prepare and post a OOP class diagram (a simple sketch only maybe via Excalidraw) before you start with code modifications.

**Comment by viralgupta** [comment]
@shalithasuranga Sir is this how we want to go?

websocketIPC class
neutralinoProcess Class (calls websocket IPC class to access its method)
clipboard Class (calls websocket IPC class to access its method)
...
...
NeutralinoApp Class which calls every class constructor!

![image](https://github.com/user-attachments/assets/21f02063-3c3a-480b-9f84-8d8c86b12f68)

**Comment by shalithasuranga** [comment]
Hello @viralgupta, thanks so much for posting this diagram. This looks great -- please continue with the development :tada: Looking forward to review a pull request for this refactoring task...

**Comment by viralgupta** [comment]
Thankyou @shalithasuranga sir for reviewing the pull request, I have started to work on this, will raise the pr soon 😇

**Comment by viralgupta** [comment]
Thankyou @shalithasuranga sir for reviewing the pull request, I have started to work on this, will raise the pr soon 😇
