### ISSUE TITLE
Use EventsEmitter by matching Neutralinojs client-side JavaScript API events namespace

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs-community/node-neutralino#7]
We need to offer event APIs, according to `Neutralino.events` namespace: https://neutralino.js.org/docs/api/events 

by implementing all functions it offers, i.e., `on()`, `off()`, `broadcast()` etc. 

Suggestion: As I slightly hinted in PR reviews, seems like we need to avoid extending `EventEmitter` and create an instance of it with a private class prop:

```js
// private class prop
ee = new EventsEmitter();

events: {
  dispatch: ...,
  broadcast: ...,
  on: this.ee.on,
  off: this.ee.off,
}

// where we emit in WS methods:
this.ee.emit(evt)

// usage
app.events.on(..
app.events.dispatch(..
//....
```

Using this approach we only expose only required methods and get the events namespace as we need.

**Comment by viralgupta** [comment]
thankyou sir for explaining the solutions, i have raise pr to implement this approach.
#8
